# Generated by Django 5.0.2 on 2024-05-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='login',
            new_name='username',
        ),
    ]
