# Generated by Django 4.2.10 on 2024-02-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='north_app.grades')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='north_app.students')),
            ],
        ),
    ]
