# Generated by Django 5.0.2 on 2024-02-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0002_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.IntegerField(choices=[(0, 'Учитель'), (1, 'Зам. Директор'), (2, 'Директор')], default=0),
        ),
    ]
