# Generated by Django 5.0.2 on 2024-05-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0003_rename_login_student_logina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='logina',
            new_name='login',
        ),
    ]
