# Generated by Django 5.0.2 on 2024-02-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0003_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Муж'), (1, 'Жен')], default=0),
        ),
    ]
