# Generated by Django 5.0.2 on 2024-02-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0004_alter_employees_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
    ]
