# Generated by Django 5.0.2 on 2024-05-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0004_rename_logina_student_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='login',
            new_name='username',
        ),
    ]
