# Generated by Django 4.2.10 on 2024-04-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0010_alter_employee_id_alter_grade_id_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
