# Generated by Django 5.0.2 on 2024-05-08 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0011_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Class_teacher',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\d{3}(?:[А-Я])?$', message='Только трехзначное число или трехзначное число с заглавной буквой в конце')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[А-Я][а-я]* [А-Я][а-я]* [А-Я][а-я]*$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий'), (4, 'Четвертый'), (5, 'Пятый'), (6, 'Шестой'), (7, 'Седьмой'), (8, 'Восьмой'), (9, 'Девятый'), (10, 'Десятый'), (11, 'Одиннадцатый')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[А-Я][а-я]* [А-Я][а-я]* [А-Я][а-я]*$')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Имя предмета должно начинаться с заглавной буквы', regex='^[А-Я][а-я]*$')]),
        ),
    ]
