# Generated by Django 5.0.2 on 2024-05-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0009_alter_employee_name_alter_student_class_name_and_more'),
        ('north_app', '0012_remove_student_password_alter_employee_class_teacher_and_more'),
    ]

    operations = [
    ]
