# Generated by Django 5.0.2 on 2024-05-15 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0013_merge_20240515_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Имя предмета должно начинаться с заглавной буквы', regex='^[А-Я][а-я\\s\\-]*$')]),
        ),
    ]
