# Generated by Django 5.0.2 on 2024-05-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('north_app', '0014_student_password_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
